# Generated by Django 5.2.8 on 2025-11-14 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayplan',
            name='data',
            field=models.DateField(db_index=True, unique_for_date='data', verbose_name='Data'),
        ),
    ]
