# Generated by Django 5.2.8 on 2025-11-19 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_taskmoment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmoment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
