# Generated by Django 5.2.12 on 2026-03-28 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_taskmoment_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TaskMoment",
        ),
    ]
